//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "automation_runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub automation_id: u64,
    pub generated_document_id: Option<u64>,
    pub finished_at: Option<DateTime>,
    pub failed: i8,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::automations::Entity",
        from = "Column::AutomationId",
        to = "super::automations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Automations,
}

impl Related<super::automations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Automations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
