//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "automations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: u64,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub query: String,
    #[sea_orm(column_type = "Text")]
    pub output_format: String,
    pub mode: u8,
    pub precise: i8,
    pub send_to: String,
    pub start_date: DateTime,
    pub repeat: String,
    pub every: u8,
    pub on_relative: i8,
    pub on_day: Option<i8>,
    pub on_day_of_week: Option<u8>,
    pub on_day_of_month: Option<u8>,
    pub on_month_of_year: Option<u8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::automation_runs::Entity")]
    AutomationRuns,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::automation_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutomationRuns.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
