//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "content_user_query")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub content_id: u64,
    pub user_query_id: u64,
    pub deleted_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Double", nullable)]
    pub metadata_relevancy_score: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub content_relevancy_score: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contents::Entity",
        from = "Column::ContentId",
        to = "super::contents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contents,
    #[sea_orm(
        belongs_to = "super::user_queries::Entity",
        from = "Column::UserQueryId",
        to = "super::user_queries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserQueries,
}

impl Related<super::contents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contents.def()
    }
}

impl Related<super::user_queries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserQueries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
