//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub content_source_id: u64,
    pub page_title: Option<String>,
    #[sea_orm(unique)]
    pub url: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub body: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text", nullable)]
    pub page_snippet: Option<String>,
    pub qdrant_sync_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_generated_document::Entity")]
    ContentGeneratedDocument,
    #[sea_orm(has_many = "super::content_generated_text::Entity")]
    ContentGeneratedText,
    #[sea_orm(
        belongs_to = "super::content_sources::Entity",
        from = "Column::ContentSourceId",
        to = "super::content_sources::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ContentSources,
    #[sea_orm(has_many = "super::content_user_query::Entity")]
    ContentUserQuery,
}

impl Related<super::content_generated_document::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentGeneratedDocument.def()
    }
}

impl Related<super::content_generated_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentGeneratedText.def()
    }
}

impl Related<super::content_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentSources.def()
    }
}

impl Related<super::content_user_query::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentUserQuery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
