//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "content_generated_document")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub content_id: u64,
    pub generated_document_id: u64,
    pub deleted_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contents::Entity",
        from = "Column::ContentId",
        to = "super::contents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contents,
    #[sea_orm(
        belongs_to = "super::generated_documents::Entity",
        from = "Column::GeneratedDocumentId",
        to = "super::generated_documents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GeneratedDocuments,
}

impl Related<super::contents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contents.def()
    }
}

impl Related<super::generated_documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedDocuments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
