//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "countries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub capital: Option<String>,
    pub citizenship: Option<String>,
    pub country_code: String,
    pub currency: Option<String>,
    pub currency_code: Option<String>,
    pub currency_sub_unit: Option<String>,
    pub currency_symbol: Option<String>,
    pub currency_decimals: Option<i32>,
    pub full_name: Option<String>,
    pub iso_3166_2: String,
    pub iso_3166_3: String,
    pub name: String,
    pub region_code: String,
    pub sub_region_code: String,
    pub eea: i8,
    pub calling_code: Option<String>,
    pub flag: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
