//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "document_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: Option<u64>,
    pub user_defined: i8,
    pub name: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub desc: String,
    pub deleted_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub use_section_descriptions: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::document_type_sections::Entity")]
    DocumentTypeSections,
}

impl Related<super::document_type_sections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentTypeSections.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
