//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "document_type_sections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub document_type_id: u64,
    pub title: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub desc: String,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::document_types::Entity",
        from = "Column::DocumentTypeId",
        to = "super::document_types::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DocumentTypes,
}

impl Related<super::document_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
