//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "failed_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub uuid: String,
    #[sea_orm(column_type = "Text")]
    pub connection: String,
    #[sea_orm(column_type = "Text")]
    pub queue: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub payload: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub exception: String,
    pub failed_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
