//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use super::sea_orm_active_enums::Type;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: u64,
    pub file_id: Option<u64>,
    pub name: String,
    pub r#type: Option<Type>,
    pub is_folder: i8,
    pub fileable_id: Option<u64>,
    pub fileable_type: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_uploads::Entity")]
    FileUploads,
    #[sea_orm(has_many = "super::user_queries::Entity")]
    UserQueries,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileUploads.def()
    }
}

impl Related<super::user_queries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserQueries.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
