//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "generated_text_uploaded_file")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub generated_text_id: u64,
    pub uploaded_file_id: u64,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::generated_texts::Entity",
        from = "Column::GeneratedTextId",
        to = "super::generated_texts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GeneratedTexts,
    #[sea_orm(
        belongs_to = "super::uploaded_files::Entity",
        from = "Column::UploadedFileId",
        to = "super::uploaded_files::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UploadedFiles,
}

impl Related<super::generated_texts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedTexts.def()
    }
}

impl Related<super::uploaded_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UploadedFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
