//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "generated_documents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: u64,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    pub finished_generating: i8,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub input_text: Option<String>,
    pub document_type_id: Option<u64>,
    pub failed: i8,
    pub user_query_id: Option<u64>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub output_format: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_generated_document::Entity")]
    ContentGeneratedDocument,
    #[sea_orm(has_many = "super::generated_document_generated_text::Entity")]
    GeneratedDocumentGeneratedText,
}

impl Related<super::content_generated_document::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentGeneratedDocument.def()
    }
}

impl Related<super::generated_document_generated_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedDocumentGeneratedText.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
