//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "generated_texts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: Option<i64>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub text: String,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    pub generated_document_id: Option<u64>,
    pub r#type: String,
    pub document_type_section_id: Option<u64>,
    pub intermediate: i8,
    pub user_query_id: Option<u64>,
    pub citation_id: Option<u16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_generated_text::Entity")]
    ContentGeneratedText,
    #[sea_orm(has_many = "super::generated_document_generated_text::Entity")]
    GeneratedDocumentGeneratedText,
    #[sea_orm(has_many = "super::generated_text_uploaded_file::Entity")]
    GeneratedTextUploadedFile,
    #[sea_orm(has_many = "super::generated_text_user_query::Entity")]
    GeneratedTextUserQuery,
}

impl Related<super::content_generated_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentGeneratedText.def()
    }
}

impl Related<super::generated_document_generated_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedDocumentGeneratedText.def()
    }
}

impl Related<super::generated_text_uploaded_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedTextUploadedFile.def()
    }
}

impl Related<super::generated_text_user_query::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedTextUserQuery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
