//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "job_batches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub total_jobs: i32,
    pub pending_jobs: i32,
    pub failed_jobs: i32,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub failed_job_ids: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub options: Option<String>,
    pub cancelled_at: Option<i32>,
    pub created_at: i32,
    pub finished_at: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
