//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub queue: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub payload: String,
    pub attempts: u8,
    pub reserved_at: Option<u32>,
    pub available_at: u32,
    pub created_at: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
