//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "podcast_episodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: i32,
    pub title: String,
    pub description: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub content: String,
    pub status: String,
    pub api_episode_id: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
