//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rss_feeds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: i32,
    pub url: String,
    pub last_post_hash: Option<String>,
    pub last_post_timestamp: DateTimeUtc,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub automated: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
