//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "short_url_visits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub short_url_id: u64,
    pub ip_address: Option<String>,
    pub operating_system: Option<String>,
    pub operating_system_version: Option<String>,
    pub browser: Option<String>,
    pub browser_version: Option<String>,
    pub referer_url: Option<String>,
    pub device_type: Option<String>,
    pub visited_at: DateTimeUtc,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::short_urls::Entity",
        from = "Column::ShortUrlId",
        to = "super::short_urls::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ShortUrls,
}

impl Related<super::short_urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShortUrls.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
