//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "short_urls")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(column_type = "Text")]
    pub destination_url: String,
    #[sea_orm(unique)]
    pub url_key: String,
    pub default_short_url: String,
    pub single_use: i8,
    pub forward_query_params: i8,
    pub track_visits: i8,
    pub redirect_status_code: i32,
    pub track_ip_address: i8,
    pub track_operating_system: i8,
    pub track_operating_system_version: i8,
    pub track_browser: i8,
    pub track_browser_version: i8,
    pub track_referer_url: i8,
    pub track_device_type: i8,
    pub activated_at: Option<DateTimeUtc>,
    pub deactivated_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::short_url_visits::Entity")]
    ShortUrlVisits,
}

impl Related<super::short_url_visits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShortUrlVisits.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
