//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "team_subscription_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub team_subscription_id: u64,
    #[sea_orm(unique)]
    pub stripe_id: String,
    pub stripe_product: String,
    pub stripe_price: String,
    pub quantity: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
