//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: u64,
    pub name: String,
    pub desc: Option<String>,
    pub personal_team: i8,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub stripe_id: Option<String>,
    pub pm_type: Option<String>,
    pub pm_last_four: Option<String>,
    pub trial_ends_at: Option<DateTimeUtc>,
    #[sea_orm(unique)]
    pub referral_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::team_invitations::Entity")]
    TeamInvitations,
}

impl Related<super::team_invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamInvitations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
