//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "team_subscriptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub team_id: u64,
    pub name: String,
    #[sea_orm(unique)]
    pub stripe_id: String,
    pub stripe_status: String,
    pub stripe_price: Option<String>,
    pub quantity: Option<i32>,
    pub trial_ends_at: Option<DateTimeUtc>,
    pub ends_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub downgrade_price_id: Option<String>,
    pub downgrade_quantity: Option<u16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
