//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "uploaded_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub path: String,
    pub user_id: u64,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub text: String,
    pub qdrant_sync_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::generated_text_uploaded_file::Entity")]
    GeneratedTextUploadedFile,
}

impl Related<super::generated_text_uploaded_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedTextUploadedFile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
