//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
    pub email: String,
    pub email_verified_at: Option<DateTimeUtc>,
    pub password: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub two_factor_secret: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub two_factor_recovery_codes: Option<String>,
    pub two_factor_confirmed_at: Option<DateTimeUtc>,
    pub remember_token: Option<String>,
    pub current_team_id: Option<u64>,
    pub profile_photo_path: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub stripe_id: Option<String>,
    pub pm_type: Option<String>,
    pub pm_last_four: Option<String>,
    pub trial_ends_at: Option<DateTimeUtc>,
    pub skipped_create_organization: i8,
    pub deleted_at: Option<DateTimeUtc>,
    pub alive: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::automations::Entity")]
    Automations,
    #[sea_orm(has_many = "super::file_uploads::Entity")]
    FileUploads,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::o_auth_identities::Entity")]
    OAuthIdentities,
    #[sea_orm(has_many = "super::user_queries::Entity")]
    UserQueries,
}

impl Related<super::automations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Automations.def()
    }
}

impl Related<super::file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileUploads.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::o_auth_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OAuthIdentities.def()
    }
}

impl Related<super::user_queries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserQueries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
