//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_queries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: u64,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub text: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    pub file_id: Option<u64>,
    pub progress: u8,
    pub failed: i8,
    pub mode: Option<u8>,
    pub precise: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub search_phrase: Option<String>,
    pub sample: i8,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub keywords: Option<Json>,
    pub output_format: Option<u16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_user_query::Entity")]
    ContentUserQuery,
    #[sea_orm(
        belongs_to = "super::files::Entity",
        from = "Column::FileId",
        to = "super::files::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Files,
    #[sea_orm(has_many = "super::generated_text_user_query::Entity")]
    GeneratedTextUserQuery,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::content_user_query::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentUserQuery.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::generated_text_user_query::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedTextUserQuery.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
