//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "websockets_statistics_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub app_id: String,
    pub peak_connection_count: i32,
    pub websocket_message_count: i32,
    pub api_message_count: i32,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
